project:
  title: "linzeyu"
author: "Linze Yu"
editor: source
format:
  html:
    theme: Cosmo
    toc: true
    fontcolor: "#34558B"
    number-sections: true
    code-overflow: wrap
    fig-cap-location: top
    title-block-style: default
    code-copy: true
    code-block-bg: "#E6EEF1"
    embed-resources: true
    execute:
      fig-dpi: 400
      fig-format: png
      echo: true
      warning: false
      error: false
      prompt: false
      message: false
      collapse: false
      comment: ""
R.options:
 knitr.graphics.auto_pdf: true
editor_options:
  markdown:
    wrap: sentence






